"""upgrade product head

Revision ID: 13da610a4624
Revises: ffa0348cce35
Create Date: 2024-08-14 18:48:35.009187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13da610a4624'
down_revision: Union[str, None] = 'ffa0348cce35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stripe_product_id', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stripe_product_id')
    # ### end Alembic commands ###
