"""upgrade product head

Revision ID: 468d1fdf48dd
Revises: c32bddf0fbb3
Create Date: 2024-07-26 13:05:53.918145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468d1fdf48dd'
down_revision: Union[str, None] = 'c32bddf0fbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('currency_base', sa.String(length=75), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'currency_base')
    # ### end Alembic commands ###
