"""upgrade product head

Revision ID: 4b004a13f7b7
Revises: cb77a8fca378
Create Date: 2024-07-30 12:28:09.517249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b004a13f7b7'
down_revision: Union[str, None] = 'cb77a8fca378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('handle', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'handle')
    # ### end Alembic commands ###
