"""update migration

Revision ID: 59328e71dc2c
Revises: 0e6101cf36ce
Create Date: 2024-07-14 19:35:06.226528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59328e71dc2c'
down_revision: Union[str, None] = '0e6101cf36ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('description', sa.String(length=800), nullable=True))
    op.add_column('collections', sa.Column('category_condition', sa.String(length=800), nullable=True))
    op.add_column('collections', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('collections', sa.Column('tag_condition', sa.String(length=800), nullable=True))
    op.add_column('collections', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collections', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'collections', 'categories', ['category_id'], ['id'])
    op.drop_column('collections', 'category_list')
    op.drop_column('collections', 'tag_list')
    op.add_column('inventory', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('on_hold', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('is_processing', sa.Boolean(), nullable=True))
    op.add_column('product_options', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_options_ibfk_1', 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'products', ['product_id'], ['id'])
    op.drop_column('product_options', 'variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('variant', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key('product_options_ibfk_1', 'product_options', 'product_variants', ['variant'], ['id'])
    op.drop_column('product_options', 'product_id')
    op.drop_column('orders', 'is_processing')
    op.drop_column('orders', 'on_hold')
    op.drop_column('inventory', 'lng')
    op.drop_column('inventory', 'lat')
    op.add_column('collections', sa.Column('tag_list', mysql.VARCHAR(length=800), nullable=True))
    op.add_column('collections', sa.Column('category_list', mysql.VARCHAR(length=800), nullable=True))
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'tag_id')
    op.drop_column('collections', 'tag_condition')
    op.drop_column('collections', 'category_id')
    op.drop_column('collections', 'category_condition')
    op.drop_column('collections', 'description')
    # ### end Alembic commands ###
