"""upgrade product head

Revision ID: 69a4171a04c7
Revises: 13da610a4624
Create Date: 2024-08-14 19:02:59.448956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a4171a04c7'
down_revision: Union[str, None] = '13da610a4624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('stripe_price_id', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'stripe_price_id')
    # ### end Alembic commands ###
