"""upgrade product title to name

Revision ID: c32bddf0fbb3
Revises: b0fc5a29344b
Create Date: 2024-07-26 11:03:24.521884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c32bddf0fbb3'
down_revision: Union[str, None] = 'b0fc5a29344b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(length=400), nullable=True))
    op.drop_column('products', 'title')
    op.add_column('team_members', sa.Column('role', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'role')
    op.add_column('products', sa.Column('title', mysql.VARCHAR(length=400), nullable=True))
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
