"""add product id to variants

Revision ID: f824cfc93c3b
Revises: 4255089c8344
Create Date: 2024-07-24 15:27:30.166817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f824cfc93c3b'
down_revision: Union[str, None] = '4255089c8344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'product_id')
    # ### end Alembic commands ###
