"""upgrade mail notifications head

Revision ID: f9c1dfa22742
Revises: aaf76047b6f0
Create Date: 2024-08-23 18:14:41.668868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c1dfa22742'
down_revision: Union[str, None] = 'aaf76047b6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_notifications', sa.Column('is_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_notifications', 'is_sent')
    # ### end Alembic commands ###
