"""upgrade payments tables head

Revision ID: ffa0348cce35
Revises: 62be2fe1a370
Create Date: 2024-08-07 11:07:34.448818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffa0348cce35'
down_revision: Union[str, None] = '62be2fe1a370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(length=800), nullable=True))
    op.add_column('orders', sa.Column('is_shipped', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'products')
    op.add_column('payment_methods', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('shipping_addresses_transactions', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('shipping_addresses_transactions', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_addresses_transactions', 'lng')
    op.drop_column('shipping_addresses_transactions', 'lat')
    op.drop_column('payment_methods', 'disabled')
    op.add_column('orders', sa.Column('products', mysql.VARCHAR(length=800), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'is_shipped')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
